### ISSUE TITLE
doubt about the project

### ISSUE THREAD

**Issue by ronald0098** [kurianbenoy/Indic-Subtitler#12]
does this project only makes subtitles for youtube videos or it can even translate the youtube videos into various other regional languages??

**Comment by aldrinjenson** [comment]
It can do translation as well. 

Feel free to paste a youtube url and then choose a different subtitle language from the dropdown.

The accuracy will be slightly off depending on the language chosen

**Comment by ronald0098** [comment]
Like if I have a video in Hindi language so can this project translate the
audio to any Indian regional language and the it will be displayed on the
GUI with the respective language which I have selected???

**Comment by aldrinjenson** [comment]
Yes @ronald0098 this should work in most cases. 
The accuracy may be slightly off though. 
Do feel free to test it out with a video of choice.
