### ISSUE TITLE
Improve blog recommendation section for Telugu subtitles

### ISSUE THREAD

**Issue by hazarathayya** [kurianbenoy/Indic-Subtitler#7]
**The current blog recommendation section lacks information on which model performs best for generating Telugu subtitles.**

Proposed Solution:

1. Testing: Conduct a test using several models (available in the advanced options) on a set of video samples containing Telugu subtitles.
2. Evaluation: Analyze the results and identify the model that delivers the most accurate subtitles.
3. Update Blog: Incorporate the findings into the blog's recommendation section, highlighting the model best suited for Telugu subtitles.

**Comment by kurianbenoy** [comment]
Closed as #8 is merged
